// <auto-generated />
using System;
using KindRegardsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KindRegardsApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220525122001_RemoveDeviceStickerModelIdFromStickers")]
    partial class RemoveDeviceStickerModelIdFromStickers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KindRegardsApi.Entity.Stickers.DeviceStickerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("StickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StickerId");

                    b.ToTable("DeviceStickers");
                });

            modelBuilder.Entity("KindRegardsApi.Entity.Stickers.StickerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("DeviceStickerEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceStickerEntityId");

                    b.ToTable("Stickers");
                });

            modelBuilder.Entity("KindRegardsApi.Entity.Stickers.DeviceStickerEntity", b =>
                {
                    b.HasOne("KindRegardsApi.Entity.Stickers.StickerEntity", "Sticker")
                        .WithMany()
                        .HasForeignKey("StickerId");

                    b.Navigation("Sticker");
                });

            modelBuilder.Entity("KindRegardsApi.Entity.Stickers.StickerEntity", b =>
                {
                    b.HasOne("KindRegardsApi.Entity.Stickers.DeviceStickerEntity", null)
                        .WithMany()
                        .HasForeignKey("DeviceStickerEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
